import type { CompiledDef, CompiledSchema, LookupEntry } from "./types.js";

const GENERATED_BANNER =
  "// @generated by @rusl-labs/zodforge — do not edit\n";

function renderRootSchemaExports(compiled: CompiledSchema): string {
  const metaVar = `${compiled.jsonImportVar}Meta`;

  return `export const ${compiled.schemaExport} = z.fromJSONSchema(${compiled.jsonImportVar} as Parameters<typeof z.fromJSONSchema>[0]).meta({
  id: ${metaVar}.$id,
  title: ${metaVar}.title,
  description: ${metaVar}.description,
  pathId: ${JSON.stringify(compiled.pathId)},
});

export type ${compiled.typeExport} = z.infer<typeof ${compiled.schemaExport}>;
export type ${compiled.typeInputExport} = z.input<typeof ${compiled.schemaExport}>;`;
}

function renderDefSchemaExports(
  compiled: CompiledSchema,
  def: CompiledDef,
): string {
  const metaFields = [
    `pathId: ${JSON.stringify(def.pathId)}`,
    def.title ? `title: ${JSON.stringify(def.title)}` : null,
    def.description ? `description: ${JSON.stringify(def.description)}` : null,
  ].filter(Boolean);

  const metaSuffix =
    metaFields.length > 0 ? `.meta({\n  ${metaFields.join(",\n  ")},\n})` : "";

  return `export const ${def.schemaExport} = z.fromJSONSchema({
  ...${compiled.jsonImportVar},
  $ref: ${JSON.stringify(def.refPath)},
} as Parameters<typeof z.fromJSONSchema>[0])${metaSuffix};

export type ${def.typeExport} = z.infer<typeof ${def.schemaExport}>;
export type ${def.typeInputExport} = z.input<typeof ${def.schemaExport}>;`;
}

export function renderSchemaFile(
  compiled: CompiledSchema,
  jsonImportPath: string,
): string {
  const metaVar = `${compiled.jsonImportVar}Meta`;
  const sections = [
    `${GENERATED_BANNER}import * as z from "zod";
import ${compiled.jsonImportVar} from "${jsonImportPath}";

const ${metaVar} = ${compiled.jsonImportVar} as {
  $id?: string;
  title?: string;
  description?: string;
};`,
  ];

  if (!compiled.isDefsOnly) {
    sections.push(renderRootSchemaExports(compiled));
  }

  for (const def of compiled.defs) {
    sections.push(renderDefSchemaExports(compiled, def));
  }

  return `${sections.join("\n\n")}\n`;
}

export function renderBarrelFile(exports: string[]): string {
  const lines = exports.map((entry) => `export * from "${entry}";`);
  return `${GENERATED_BANNER}${lines.join("\n")}\n`;
}

export function renderLookupFile(entries: LookupEntry[]): string {
  const importsByPath = new Map<string, Set<string>>();

  for (const entry of entries) {
    const existing = importsByPath.get(entry.importPath) ?? new Set<string>();
    existing.add(entry.schemaExport);
    importsByPath.set(entry.importPath, existing);
  }

  const imports = [...importsByPath.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([importPath, exports]) => {
      const namedExports = [...exports].sort((left, right) =>
        left.localeCompare(right),
      );
      return `import { ${namedExports.join(", ")} } from "${importPath}";`;
    })
    .join("\n");

  const byPathEntries = entries
    .map(
      (entry) =>
        `  ${JSON.stringify(entry.pathId)}: ${entry.schemaExport},`,
    )
    .sort((left, right) => left.localeCompare(right))
    .join("\n");

  const byIdEntries = entries
    .filter((entry) => entry.id)
    .map(
      (entry) => `  ${JSON.stringify(entry.id)}: ${entry.schemaExport},`,
    )
    .sort((left, right) => left.localeCompare(right))
    .join("\n");

  return `${GENERATED_BANNER}import type { ZodType } from "zod";
${imports}

export const byPath = {
${byPathEntries}
} as const;

export const byId = {
${byIdEntries}
} as const;

export function getSchemaByIdentifier(id: string): ZodType | undefined {
  return byPath[id as keyof typeof byPath] ?? byId[id as keyof typeof byId];
}
`;
}

export function renderRootIndexFile(
  topLevelEntries: string[],
): string {
  const exports = [...topLevelEntries, "./_lookup"];
  return renderBarrelFile(exports);
}

export function renderManifestFile(payload: object): string {
  return `${JSON.stringify(payload, null, 2)}\n`;
}
