import type { CompiledSchema } from "./types.js";

const GENERATED_BANNER =
  "// @generated by @rusl-labs/zodforge — do not edit\n";

export function renderSchemaFile(
  compiled: CompiledSchema,
  jsonImportPath: string,
): string {
  const metaVar = `${compiled.jsonImportVar}Meta`;

  return `${GENERATED_BANNER}import * as z from "zod";
import ${compiled.jsonImportVar} from "${jsonImportPath}";

const ${metaVar} = ${compiled.jsonImportVar} as {
  $id?: string;
  title?: string;
  description?: string;
};

export const ${compiled.schemaExport} = z.fromJSONSchema(${compiled.jsonImportVar} as Parameters<typeof z.fromJSONSchema>[0]).meta({
  id: ${metaVar}.$id,
  title: ${metaVar}.title,
  description: ${metaVar}.description,
  pathId: ${JSON.stringify(compiled.pathId)},
});

export type ${compiled.typeExport} = z.infer<typeof ${compiled.schemaExport}>;
export type ${compiled.typeInputExport} = z.input<typeof ${compiled.schemaExport}>;
`;
}

export function renderBarrelFile(exports: string[]): string {
  const lines = exports.map((entry) => `export * from "${entry}";`);
  return `${GENERATED_BANNER}${lines.join("\n")}\n`;
}

export function renderLookupFile(schemas: CompiledSchema[]): string {
  const imports = schemas
    .map((schema) => {
      const importPath = `./${schema.pathId}`.replace(/\\/g, "/");
      return `import { ${schema.schemaExport} } from "${importPath}";`;
    })
    .join("\n");

  const byPathEntries = schemas
    .map(
      (schema) =>
        `  ${JSON.stringify(schema.pathId)}: ${schema.schemaExport},`,
    )
    .join("\n");

  const byIdEntries = schemas
    .filter((schema) => schema.id)
    .map(
      (schema) => `  ${JSON.stringify(schema.id)}: ${schema.schemaExport},`,
    )
    .join("\n");

  return `${GENERATED_BANNER}import type { ZodType } from "zod";
${imports}

export const byPath = {
${byPathEntries}
} as const;

export const byId = {
${byIdEntries}
} as const;

export function getSchemaByIdentifier(id: string): ZodType | undefined {
  return byPath[id as keyof typeof byPath] ?? byId[id as keyof typeof byId];
}
`;
}

export function renderRootIndexFile(
  topLevelEntries: string[],
): string {
  const exports = [...topLevelEntries, "./_lookup"];
  return renderBarrelFile(exports);
}

export function renderManifestFile(payload: object): string {
  return `${JSON.stringify(payload, null, 2)}\n`;
}
