import type {
  CompiledDef,
  CompiledSchema,
  RawLookupEntry,
  ZodLookupEntry,
} from "./types.js";
import { rawSiblingImportPath } from "./naming.js";
import {
  compileHelperImportPath,
  zodSiblingImportPath,
} from "./refs.js";

const GENERATED_BANNER =
  "// @generated by @rusl-labs/zodforge — do not edit\n";

export function renderRawFile(
  compiled: CompiledSchema,
  jsonImportPath: string,
): string {
  return `${GENERATED_BANNER}import ${compiled.jsonImportVar} from "${jsonImportPath}";

/** Full JSON Schema document as vendored — not limited to Zod's compile surface. */
export const ${compiled.rawExport} = ${compiled.jsonImportVar};

export type ${compiled.rawTypeExport} = typeof ${compiled.rawExport};
`;
}

function renderExternalImports(compiled: CompiledSchema): string {
  if (compiled.externalDeps.length === 0) {
    return "";
  }

  const byModule = new Map<
    string,
    { values: Set<string>; types: Set<string> }
  >();
  for (const dep of compiled.externalDeps) {
    const importPath = zodSiblingImportPath(compiled.pathId, dep.pathId);
    const existing = byModule.get(importPath) ?? {
      values: new Set<string>(),
      types: new Set<string>(),
    };
    existing.values.add(dep.zodExport);
    existing.types.add(dep.typeExport);
    byModule.set(importPath, existing);
  }

  return [...byModule.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([importPath, { values, types }]) => {
      const names = [
        ...[...values].sort((a, b) => a.localeCompare(b)),
        ...[...types]
          .sort((a, b) => a.localeCompare(b))
          .map((name) => `type ${name}`),
      ];
      return `import { ${names.join(", ")} } from "${importPath}";`;
    })
    .join("\n");
}

function renderExternalMap(compiled: CompiledSchema): string {
  if (compiled.externalDeps.length === 0) {
    return "{}";
  }

  const entries = compiled.externalDeps
    .map((dep) => `  ${JSON.stringify(dep.ref)}: ${dep.zodExport},`)
    .join("\n");
  return `{\n${entries}\n}`;
}

function renderTypeExports(
  typeExport: string,
  typeInputExport: string,
  inferredType: string,
): string {
  return `export type ${typeExport} = ${inferredType};
export type ${typeInputExport} = ${typeExport};`;
}

function renderRootZodExports(compiled: CompiledSchema): string {
  const metaVar = `${compiled.rawExport}Meta`;
  const types = renderTypeExports(
    compiled.typeExport,
    compiled.typeInputExport,
    compiled.inferredType,
  );
  const annotation = `z.ZodType<${compiled.typeExport}, ${compiled.typeExport}>`;

  if (compiled.hasExternalRefs) {
    return `${types}

export const ${compiled.zodExport}: ${annotation} = compileJsonSchema(
  ${compiled.rawExport} as Parameters<typeof compileJsonSchema>[0],
  { external: ${renderExternalMap(compiled)} },
).meta({
  id: ${metaVar}.$id,
  title: ${metaVar}.title,
  description: ${metaVar}.description,
  pathId: ${JSON.stringify(compiled.pathId)},
}) as ${annotation};`;
  }

  return `${types}

export const ${compiled.zodExport}: ${annotation} = z
  .fromJSONSchema(
    ${compiled.rawExport} as Parameters<typeof z.fromJSONSchema>[0],
  )
  .meta({
    id: ${metaVar}.$id,
    title: ${metaVar}.title,
    description: ${metaVar}.description,
    pathId: ${JSON.stringify(compiled.pathId)},
  }) as ${annotation};`;
}

function renderDefExportSchemaObject(
  compiled: CompiledSchema,
  def: CompiledDef,
): string {
  const raw = compiled.rawExport;
  const defsKey = def.refPath.startsWith("#/definitions/")
    ? "definitions"
    : "$defs";
  const fields: string[] = [];

  if (compiled.rawJson.$schema !== undefined) {
    fields.push(`$schema: ${raw}.$schema`);
  }
  if (compiled.rawJson.$id !== undefined) {
    fields.push(`$id: ${raw}.$id`);
  }
  fields.push(`${defsKey}: ${raw}.${defsKey}`);
  fields.push(`$ref: ${JSON.stringify(def.refPath)}`);

  return `{
    ${fields.join(",\n    ")},
  }`;
}

function renderDefZodExports(
  compiled: CompiledSchema,
  def: CompiledDef,
): string {
  const metaFields = [
    `pathId: ${JSON.stringify(def.pathId)}`,
    def.title ? `title: ${JSON.stringify(def.title)}` : null,
    def.description ? `description: ${JSON.stringify(def.description)}` : null,
  ].filter(Boolean);

  const metaSuffix =
    metaFields.length > 0 ? `.meta({\n  ${metaFields.join(",\n  ")},\n})` : "";

  const types = renderTypeExports(
    def.typeExport,
    def.typeInputExport,
    def.inferredType,
  );
  const annotation = `z.ZodType<${def.typeExport}, ${def.typeExport}>`;
  const schemaObject = renderDefExportSchemaObject(compiled, def);

  if (compiled.hasExternalRefs) {
    return `${types}

export const ${def.zodExport}: ${annotation} = compileJsonSchema(
  ${schemaObject} as Parameters<typeof compileJsonSchema>[0],
  { external: ${renderExternalMap(compiled)} },
)${metaSuffix} as ${annotation};`;
  }

  return `${types}

export const ${def.zodExport}: ${annotation} = z.fromJSONSchema(
  ${schemaObject} as Parameters<typeof z.fromJSONSchema>[0],
)${metaSuffix} as ${annotation};`;
}

export function renderZodFile(compiled: CompiledSchema): string {
  const rawImportPath = rawSiblingImportPath(compiled.pathId);
  const metaVar = `${compiled.rawExport}Meta`;
  const externalImports = renderExternalImports(compiled);

  const headerLines = [
    `${GENERATED_BANNER}import * as z from "zod";`,
  ];

  if (compiled.hasExternalRefs) {
    headerLines.push(
      `import { compileJsonSchema } from "${compileHelperImportPath(compiled.pathId)}";`,
    );
  }

  headerLines.push(
    `import { ${compiled.rawExport} } from "${rawImportPath}";`,
  );

  if (externalImports) {
    headerLines.push(externalImports);
  }

  headerLines.push(
    "",
    `const ${metaVar} = ${compiled.rawExport} as {`,
    "  $id?: string;",
    "  title?: string;",
    "  description?: string;",
    "};",
  );

  const sections = [headerLines.join("\n")];

  if (!compiled.isDefsOnly) {
    sections.push(renderRootZodExports(compiled));
  }

  for (const def of compiled.defs) {
    sections.push(renderDefZodExports(compiled, def));
  }

  return `${sections.join("\n\n")}\n`;
}

export function renderCompileHelperFile(source: string): string {
  // Drop the file's leading block comment noise is fine to keep; prefix banner.
  const body = source.replace(/^\/\*\*[\s\S]*?\*\/\s*/, "");
  return `${GENERATED_BANNER}${body}`;
}

export function renderBarrelFile(exports: string[]): string {
  const lines = exports.map((entry) => `export * from "${entry}";`);
  return `${GENERATED_BANNER}${lines.join("\n")}\n`;
}

function renderLookupImports<T extends string>(
  entries: Array<{ importPath: string; exportName: T }>,
  getExportName: (entry: { importPath: string; exportName: T }) => T,
): string {
  const importsByPath = new Map<string, Set<string>>();

  for (const entry of entries) {
    const existing = importsByPath.get(entry.importPath) ?? new Set<string>();
    existing.add(getExportName(entry));
    importsByPath.set(entry.importPath, existing);
  }

  return [...importsByPath.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([importPath, exports]) => {
      const namedExports = [...exports].sort((left, right) =>
        left.localeCompare(right),
      );
      return `import { ${namedExports.join(", ")} } from "${importPath}";`;
    })
    .join("\n");
}

export function renderZodLookupFile(entries: ZodLookupEntry[]): string {
  const imports = renderLookupImports(
    entries.map((entry) => ({
      importPath: entry.importPath,
      exportName: entry.zodExport,
    })),
    (entry) => entry.exportName,
  );

  const byPathEntries = entries
    .map(
      (entry) => `  ${JSON.stringify(entry.pathId)}: ${entry.zodExport},`,
    )
    .sort((left, right) => left.localeCompare(right))
    .join("\n");

  const byIdEntries = entries
    .filter((entry) => entry.id)
    .map((entry) => `  ${JSON.stringify(entry.id)}: ${entry.zodExport},`)
    .sort((left, right) => left.localeCompare(right))
    .join("\n");

  return `${GENERATED_BANNER}import type { ZodType } from "zod";
${imports}

export const byPath = {
${byPathEntries}
} as const;

export const byId = {
${byIdEntries}
} as const;

export function getSchemaByIdentifier(id: string): ZodType | undefined {
  return byPath[id as keyof typeof byPath] ?? byId[id as keyof typeof byId];
}
`;
}

export function renderRawLookupFile(entries: RawLookupEntry[]): string {
  const imports = renderLookupImports(
    entries.map((entry) => ({
      importPath: entry.importPath,
      exportName: entry.rawExport,
    })),
    (entry) => entry.exportName,
  );

  const byPathEntries = entries
    .map(
      (entry) => `  ${JSON.stringify(entry.pathId)}: ${entry.rawExport},`,
    )
    .sort((left, right) => left.localeCompare(right))
    .join("\n");

  const byIdEntries = entries
    .filter((entry) => entry.id)
    .map((entry) => `  ${JSON.stringify(entry.id)}: ${entry.rawExport},`)
    .sort((left, right) => left.localeCompare(right))
    .join("\n");

  return `${GENERATED_BANNER}${imports}

export const rawByPath = {
${byPathEntries}
} as const;

export const rawById = {
${byIdEntries}
} as const;

export function getRawSchemaByIdentifier(
  id: string,
): (typeof rawByPath)[keyof typeof rawByPath] | undefined {
  return (
    rawByPath[id as keyof typeof rawByPath] ??
    rawById[id as keyof typeof rawById]
  );
}
`;
}

export function renderRootIndexFile(topLevelEntries: string[]): string {
  const exports = [...topLevelEntries, "./_lookup.raw", "./_lookup.zod"];
  return renderBarrelFile(exports);
}

export function renderManifestFile(payload: object): string {
  return `${JSON.stringify(payload, null, 2)}\n`;
}
